services:
  patient-intake:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - type: bind
        source: ./.streamlit/secrets.toml
        target: /app/.streamlit/secrets.toml
        read_only: true
      - type: bind
        source: ./.env
        target: /app/.env
        read_only: true
    environment:
      - SERVICE_TOKEN=${SERVICE_TOKEN}
      - CATALOGUE_URL=${CATALOGUE_URL}
      - PATIENT_ADD_URL=${PATIENT_ADD_URL}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    env_file:
      - .env
    restart: unless-stopped
